# Configuration for demos (specifying all the paths)

# ----------------------------------------------
# Experiment definition
#


# Demo 1: Generating different types of data from the LiDAR scan
Demo1:
  # the folder of raw LiDAR scans
  scan_folder: "/home/cel/data/kitti/sequences/07/velodyne"
  # the folder of raw semantic predictions
  # semantic_folder: "data/semantic_probs"
  # the folder to store the generated data
  dst_folder: "/home/cel/data/kitti/sequences/07"


# Demo 2: Inferring overlap and relative yaw angle between two LiDAR scans
Demo2:
  # path of Network configuration file
  network_config: "config/network.yml"
  # sepecify paths of two scans
  scan1_path: "data/scans/000000.bin"
  scan2_path: "data/scans/000001.bin"
  # seq label for inferring
  infer_seqs: "preprocess_data_demo"

# Demo 3: Loop closure detection
Demo3:
  # path of Network configuration file
  network_config: "config/network.yml"
  # sepecify paths
  # path of poses
  poses_file: "data/07/poses.txt"
  # path of calibration file of the dataset
  calib_file: "data/07/calib.txt"
  # path of raw LiDAR scan folder
  scan_folder: "data/07/velodyne"
  # path of covariance
  covariance_file: "data/07/covariance.txt"
  # seq label for inferring
  infer_seqs: "07"

# Demo4: Generating ground truth overlap and yaw for training and testing
Demo4:
  # sepecify paths
  # path of poses
  seq: "08"
  poses_file: "/home/cel/data/kitti/sequences/08/poses.txt"
  # poses_file: "/home/cel/CURLY/code/DockerFolder/data/kitti/sequences/08/poses.txt"
  # path of calibration file of the dataset
  calib_file: "/home/cel/data/kitti/sequences/08/calib.txt"
  # calib_file: "/home/cel/CURLY/code/DockerFolder/data/kitti/sequences/08/calib.txt"
  # path of raw LiDAR scan folder
  scan_folder: "/home/cel/data/kitti/sequences/08/velodyne"
  # scan_folder: "/home/cel/CURLY/code/DockerFolder/data/kitti/sequences/08/velodyne"
  # the folder to store the generated data
  # dst_folder: "data/preprocess_data_demo"
  dst_folder: "/home/cel/data/kitti/sequences/08"
  function_angle_file: ["/home/cel/data/kitti/sequences/08/function_angle/08_0_1399.csv",
                        "/home/cel/data/kitti/sequences/08/function_angle/08_1400_2000.csv",
                        "/home/cel/data/kitti/sequences/08/function_angle/08_2001_2468.csv",
                        "/home/cel/data/kitti/sequences/08/function_angle/08_2469_2849.csv",
                        "/home/cel/data/kitti/sequences/08/function_angle/08_2469_2849.csv",
                        "/home/cel/data/kitti/sequences/08/function_angle/08_2850_3149.csv",
                        "/home/cel/data/kitti/sequences/08/function_angle/08_3150_3399.csv",
                        "/home/cel/data/kitti/sequences/08/function_angle/08_3400_3599.csv",
                        "/home/cel/data/kitti/sequences/08/function_angle/08_3600_3699.csv",
                        "/home/cel/data/kitti/sequences/08/function_angle/08_3700_3799.csv",
                        "/home/cel/data/kitti/sequences/08/function_angle/08_3800_3899.csv",
                        "/home/cel/data/kitti/sequences/08/function_angle/08_3900_4070.csv"]
  # function_angle_file: ["/home/cel/data/kitti/sequences/06/function_angle/06_all.csv"]
  # function_angle_file: ["/home/cel/data/kitti/sequences/05/function_angle/05_0_1399.csv",
  #                       "/home/cel/data/kitti/sequences/05/function_angle/05_1400_2010.csv",
  #                       "/home/cel/data/kitti/sequences/05/function_angle/05_2011_2456.csv",
  #                       "/home/cel/data/kitti/sequences/05/function_angle/05_2457_2760.csv"]
  # function_angle_file: ["/home/cel/data/kitti/sequences/03/function_angle/03_all.csv"]
  # function_angle_file: ["/home/cel/data/kitti/sequences/00/function_angle/00_0_1399.csv", 
  #                       "/home/cel/data/kitti/sequences/00/function_angle/00_1400_1999.csv", 
  #                       "/home/cel/data/kitti/sequences/00/function_angle/00_2000_2399.csv", 
  #                       "/home/cel/data/kitti/sequences/00/function_angle/00_2400_2799.csv", 
  #                       "/home/cel/data/kitti/sequences/00/function_angle/00_2800_3099.csv", 
  #                       "/home/cel/data/kitti/sequences/00/function_angle/00_3100_3199.csv", 
  #                       "/home/cel/data/kitti/sequences/00/function_angle/00_3200_3299.csv", 
  #                       "/home/cel/data/kitti/sequences/00/function_angle/00_3300_3499.csv", 
  #                       "/home/cel/data/kitti/sequences/00/function_angle/00_3500_3699.csv", 
  #                       "/home/cel/data/kitti/sequences/00/function_angle/00_3700.csv", 
  #                       "/home/cel/data/kitti/sequences/00/function_angle/00_3800.csv", 
  #                       "/home/cel/data/kitti/sequences/00/function_angle/00_3900.csv", 
  #                       "/home/cel/data/kitti/sequences/00/function_angle/00_4000.csv", 
  #                       "/home/cel/data/kitti/sequences/00/function_angle/00_4100.csv", 
  #                       "/home/cel/data/kitti/sequences/00/function_angle/00_4200.csv", 
  #                       "/home/cel/data/kitti/sequences/00/function_angle/00_4300.csv", 
  #                       "/home/cel/data/kitti/sequences/00/function_angle/00_4400.csv", 
  #                       "/home/cel/data/kitti/sequences/00/function_angle/00_4500.csv"]
  # precomputed_file: "/home/cel/data/kitti/sequences/00/ground_truth_overlap/ground_truth_mapping_overlap.npy"


