# the folder of raw LiDAR scans
seq: "06"
scan_folder: "/home/cel/data/kitti/sequences/06/velodyne"
# scan_folder: "/home/cel/media/data/kitti/sequences/03/velodyne"

# the folder of raw semantic predictions
# semantic_folder: "data/semantic_probs"

# the folder to store the generated data
dst_folder: "/home/cel/data/kitti/sequences/06"
# dst_folder: "/home/cel/media/data/kitti/sequences/03"
